version: '3'

networks:
  elk:

volumes:
  elasticsearch:
    driver: local

services:

  elasticsearch:
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    networks:
      elk: null
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw

  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.1
    depends_on:
      - elasticsearch
    networks:
      elk: null
    ports:
      - 9300:9300
    volumes:
      - ./etc/logstash/pipeline:/usr/share/logstash/pipeline:ro

  kibana:
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
    image: docker.elastic.co/kibana/kibana:6.5.1
    networks:
      elk: null
    ports:
      - 5601:5601
